version: '2.2'

services:
  apache2-phreakmail:

  mysql-phreakmail:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DBROOT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  php-fpm-phreakmail:
    depends_on:
      mysql-phreakmail:
        condition: service_healthy
      unbound-phreakmail:
        condition: service_healthy
    command: >
      sh -c "echo 'Starting PHP-FPM directly' &&
             php-fpm -d date.timezone=${TZ} -d expose_php=0"

  rspamd-phreakmail:

  clamd-phreakmail:

  keydb-phreakmail:
    depends_on:
      unbound-phreakmail:
        condition: service_healthy


  django-phreakmail:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mysql-phreakmail:
        condition: service_healthy
      unbound-phreakmail:
        condition: service_healthy
      keydb-phreakmail:
        condition: service_started
    environment:
      DB_NAME: ${DBNAME}
      DB_USER: ${DBUSER}
      DB_PASSWORD: ${DBPASS}
      DB_HOST: mysql-phreakmail
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: phreakmail.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-change-this-in-production}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      PHREAKMAIL_HOSTNAME: ${PHREAKMAIL_HOSTNAME}
      TZ: ${TZ}
      KEYDB_HOST: keydb-phreakmail
      KEYDB_PORT: 6379
      KEYDB_PASSWORD: ${KEYDBPASS:-}
      ADDITIONAL_SERVER_NAMES: ${ADDITIONAL_SERVER_NAMES:-}
    volumes:
      - ./django_project:/app
      - django-static:/app/staticfiles
    command: >
      bash -c "
               echo 'Waiting for MySQL to be ready...' &&
               apt-get update && apt-get install -y netcat-openbsd &&
               while ! nc -z mysql-phreakmail 3306; do
                 echo 'MySQL is unavailable - sleeping'
                 sleep 5
               done &&
               echo 'MySQL is ready!' &&
               # Skip migrations entirely
               # python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn phreakmail.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - phreakmail-network

  rainloop-phreakmail:
    image: hardware/rainloop:latest
    restart: always
    depends_on:
      mysql-phreakmail:
        condition: service_healthy
      unbound-phreakmail:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - RAINLOOP_HOSTNAME=${PHREAKMAIL_HOSTNAME}
      - RAINLOOP_DB_MYSQL_HOST=mysql-phreakmail
      - RAINLOOP_DB_MYSQL_PORT=3306
      - RAINLOOP_DB_MYSQL_USER=${DBUSER}
      - RAINLOOP_DB_MYSQL_PASSWORD=${DBPASS}
      - RAINLOOP_DB_MYSQL_NAME=${DBNAME}
    volumes:
      - ./data/rainloop:/rainloop/data
    networks:
      - phreakmail-network

volumes:
  django-static:
