version: '3'

services:
  django-phreakmail:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql-phreakmail
      - redis-phreakmail
      - netfilter-phreakmail
    environment:
      - DB_NAME=${DBNAME}
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASS}
      - DB_HOST=mysql-phreakmail
      - DB_PORT=3306
      - DJANGO_SETTINGS_MODULE=phreakmail.settings
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-change-this-in-production}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - PHREAKMAIL_HOSTNAME=${PHREAKMAIL_HOSTNAME}
      - TZ=${TZ}
      - REDIS_HOST=redis-phreakmail
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDISPASS}
      - ADDITIONAL_SERVER_NAMES=${ADDITIONAL_SERVER_NAMES:-}
    volumes:
      - ./django_project:/app
      - django-static:/app/staticfiles
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn phreakmail.wsgi:application --bind 0.0.0.0:8000"
    networks:
      phreakmail-network:
        aliases:
          - django-phreakmail

# Add this volume to the main volumes section in docker-compose.yml
volumes:
  django-static:
